<?xml version="1.0"?>
<!--
Copyright 2021 RUVU Robotics B.V.
-->

<package format="2">
  <name>ruvu_mcl</name>
  <version>0.0.0</version>
  <description>The ruvu_mcl package</description>

  <maintainer email="paul@ruvu.nl">Paul Verhoeckx</maintainer>
  <maintainer email="ramon@ruvu.nl">Ramon Wijnands</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>libgnuplot-iostream-dev</depend>
  <depend>rosbag2</depend>
  <depend>rclcpp</depend>
  <depend>ruvu_mcl_msgs</depend>
  <depend>tf2_eigen</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>generate_parameter_library</depend>
  <depend>rclcpp_components</depend>

  <build_depend>libkdtree++-dev</build_depend>

  <exec_depend>graphicsmagick</exec_depend>

  <test_depend>ament_clang_format</test_depend>
  <test_depend>ament_cmake_cppcheck</test_depend>
  <test_depend>ament_cmake_cpplint</test_depend>
  <test_depend>ament_cmake_lint_cmake</test_depend>
  <test_depend>ament_cmake_xmllint</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>benchmark</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
